services:
  - type: web
    name: autobI-tool
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyBMfK_Vj4acUcMAglRdtZ3OmrKr82dLzts
